[package]
name = "citadels"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.7.2", features = ["ws"] }
axum-extra = { version = "0.9.0", features = ["cookie-private"] }
futures = "0.3.30"
http = "1.0.0"
load-dotenv = "0.1.2"
minijinja = { version = "1.0.10", features = ["loader"] }
serde = { version = "1.0.193", features = ["serde_derive"] }
template-fragments = "0.2.0"
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread"] }
tower = "0.4.13"
tower-http = { version = "0.5.0", features = ["fs", "trace"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
uuid = { version = "1.6.1", features = ["v4"] }
