[package]
name = "citadels"
edition = "2021"
default-run = "citadels"
version = "0.7.1"

[[bin]]
name = "citadels"
path = "src/main.rs" 

[dependencies]
askama = { version = "0.12.1", default-features = false }
axum = { version = "0.7.2", features = ["ws"] }
axum-extra = { version = "0.9.0", features = ["cookie-private"] }
futures = "0.3.30"
http = "1.0.0"
rand = "0.8.5"
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1.14"
tower = "0.4.13"
tower-http = { version = "0.5.0", features = ["fs", "trace"] }
uuid = { version = "1.6.1", features = ["v4"] }
log = "0.4.20"
env_logger = { version = "0.10.1", features = ["color"] }
rand_xoshiro = "0.6.0"
rand_core = { version = "0.6.4", features = ["getrandom"] }
serde = { version = "1.0.195", features = ["derive","rc"] }
serde_json = "1.0.111"
time = "0.3.31"
dotenv = { version = "0.15.0", optional = true }
axum-core = "0.4.3"
serde_with = "3.5.0"
tracing-subscriber = { version ="0.3.18", features = ["fmt"], default-features = false }
tracing = { version = "0.1.40", default-features = false }
macros = { path = "./macros"}
reqwest = { version = "0.12.4", features = ["json"], default-features = false }
anyhow = { version = "1.0.83", default-features = true }
axum-macros = { version = "0.4.1", optional = true}
maud = { version = "0.26.0", features = ["axum"], default-features = false}

[features]
dev = ["dep:axum-macros"]
dotenv = ["dep:dotenv"]

# https://old.reddit.com/r/rust/comments/gvrgca/this_is_a_neat_trick_for_getting_good_runtime/
[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 0
