[package]
name = "citadels"
edition = "2021"
version = "0.7.1"
default-run = "citadels"

[package.metadata.cargo-machete]
ignored = ["tower"]

[dependencies]
async-trait = "0.1.80"
axum-core = "0.4.3"
log = "0.4.20"
percent-encoding = "2.3.1"
rand_xoshiro = "0.6.0"
serde_json = "1.0.111"
serde_with = "3.5.0"
thiserror = "1.0.61"
time = "0.3.31"
tower = "0.4.13"
tower-cookies = "0.10.0"
tower-layer = "0.3.2"
tower-service = "0.3.2"
macros = { path = "./macros" }
pkce = { path = "./vendor/pkce" }

[dependencies.tower-livereload]
version = "0.9.2"
default-features = false
optional = true

[dependencies.anyhow]
version = "1.0.83"
features = ["std", "backtrace"]
default-features = false

[dependencies.arcstr]
version = "1.2.0"
features = ["serde"]
default-features = false

[dependencies.askama]
version = "0.12.1"
features = []
default-features = false

[dependencies.axum]
version = "0.7.2"
features = ["ws", "macros"]

[dependencies.dotenv]
version = "0.15.0"
features = []
optional = true

[dependencies.env_logger]
version = "0.10.1"
features = ["color"]

[dependencies.futures]
version = "0.3.30"
features = []
default-features = false

[dependencies.http]
version = "1.0.0"
features = []
default-features = false

[dependencies.jsonwebtoken]
version = "9.3.0"
features = []
default-features = false


[dependencies.maud]
version = "0.26.0"
features = ["axum"]
default-features = false


[dependencies.rand]
version = "0.8.5"
features = []
default-features = false

[dependencies.rand_core]
version = "0.6.4"
features = ["getrandom"]

[dependencies.reqwest]
version = "0.12.4"
features = ["json"]
default-features = false

[dependencies.serde]
version = "1.0.195"
features = ["derive"]

[dependencies.sqlx]
 version = "0.7.4"
 features = ["runtime-tokio","postgres"]
 default-features = false 

[dependencies.tokio]
version = "1.35.1"
features = ["macros", "rt-multi-thread"]

[dependencies.tokio-stream]
version = "0.1.14"
features = []
default-features = false

[dependencies.tower-http]
version = "0.5.0"
features = ["fs"]
default-features = false
optional = true

[dependencies.tracing]
version = "0.1.40"
features = []
default-features = false

[dependencies.uuid]
version = "1.8.0"
features = ["v4"]
default-features = false

[features]
dev = ["dep:tower-http", "dep:tower-livereload"]
dotenv = ["dep:dotenv"]

[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3

[[bin]]
path = "src/main.rs"
name = "citadels"
required-features = []
