[package]
name = "citadels_openapi_spec_gen"
version = "0.1.0"
edition = "2024"

[dependencies]
citadels = { version = "0.0.0", path = "../citadels" }
serde_json = "1.0.140"

[build-dependencies]
citadels_api = { version = "0.1.0", path = "../citadels_api" }
