create table "public"."games" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "state" jsonb not null,
    PRIMARY KEY(id)
);


alter table "public"."games" enable row level security;

create table "public"."hands" (
    "game_id" bigint not null references "public"."games"(id),
    "user_id" uuid not null references "auth"."users"(id),
    PRIMARY KEY(game_id, user_id)
);


alter table "public"."hands" enable row level security;

grant delete on table "public"."games" to "anon";

grant insert on table "public"."games" to "anon";

grant references on table "public"."games" to "anon";

grant select on table "public"."games" to "anon";

grant trigger on table "public"."games" to "anon";

grant truncate on table "public"."games" to "anon";

grant update on table "public"."games" to "anon";

grant delete on table "public"."games" to "authenticated";

grant insert on table "public"."games" to "authenticated";

grant references on table "public"."games" to "authenticated";

grant select on table "public"."games" to "authenticated";

grant trigger on table "public"."games" to "authenticated";

grant truncate on table "public"."games" to "authenticated";

grant update on table "public"."games" to "authenticated";

grant delete on table "public"."games" to "service_role";

grant insert on table "public"."games" to "service_role";

grant references on table "public"."games" to "service_role";

grant select on table "public"."games" to "service_role";

grant trigger on table "public"."games" to "service_role";

grant truncate on table "public"."games" to "service_role";

grant update on table "public"."games" to "service_role";

grant delete on table "public"."hands" to "anon";

grant insert on table "public"."hands" to "anon";

grant references on table "public"."hands" to "anon";

grant select on table "public"."hands" to "anon";

grant trigger on table "public"."hands" to "anon";

grant truncate on table "public"."hands" to "anon";

grant update on table "public"."hands" to "anon";

grant delete on table "public"."hands" to "authenticated";

grant insert on table "public"."hands" to "authenticated";

grant references on table "public"."hands" to "authenticated";

grant select on table "public"."hands" to "authenticated";

grant trigger on table "public"."hands" to "authenticated";

grant truncate on table "public"."hands" to "authenticated";

grant update on table "public"."hands" to "authenticated";

grant delete on table "public"."hands" to "service_role";

grant insert on table "public"."hands" to "service_role";

grant references on table "public"."hands" to "service_role";

grant select on table "public"."hands" to "service_role";

grant trigger on table "public"."hands" to "service_role";

grant truncate on table "public"."hands" to "service_role";

grant update on table "public"."hands" to "service_role";


